spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookmarket
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        format_sql: true
flyway:
  #  baselineOnMigrate: true
  locations: db/migration
